syntax = "proto3";

package com.fivetran.query_cache;

service SelectorService {
    rpc GetStateSelection(SelectorRequest) returns (SelectorResponse);
}

message SelectorRequest {
    string target = 1;
    SelectorCriteria selector_criteria = 2;
    string project_id = 3;
    repeated DbtNodeData nodes = 4;
}

enum SelectorCriteria {
    SC_UNSPECIFIED = 0;
    MODIFIED = 1;
    NEW = 2;
    UNMODIFIED = 3;
    OLD = 4;
    BODY = 5;
    CONFIGS = 6;
    RELATION = 7;
    PERSISTED_DESCRIPTIONS = 8;
    MACROS = 9;
    CONTRACT = 10;
}

message SelectorResponse {
    repeated string node_unique_ids = 1;
}

message DbtNodeData {
    string node_unique_id = 1;
    string node_hash = 2;
    optional string node_body_hash = 3;
    optional string node_configs_hash = 4;
    optional string node_persisted_descriptions_hash = 5;
    optional string node_macros_hash = 6;
    optional string node_contract_hash = 7;
    optional string node_database_representation = 8;
}